Tweak examples of Section O
w3c/ttml1 pull request #257
Opened 2017-11-14 21:38 UTC by palemieux

Close #225, close #254

2017-11-17 16:19 UTC, nigelmegitt approved these changes
Just one comment - it's not bad enough to request a change per se, but @palemieux and @mikedo might want to have a look at the pop on example and consider if it is really helpful to put `tts:displayAlign` on a 1 line region.

2017-11-17 16:19 UTC, nigelmegitt commented on spec/examples/ex2-pop-on.xml
> +      <region xml:id="r2" tts:color="yellow" tts:origin="10c 8c" tts:extent="40c 1c" tts:displayAlign="after"/>
I don't think this is actively harmful but it is unnecessary - the region's extent is only `1c` high. Adding this detail could be confusing.

2017-11-17 16:33 UTC, palemieux commented
> I don't think this is actively harmful but it is unnecessary - the region's extent is only 1c high. Adding this detail could be confusing.

Yes. I also wondered if a `1c` height is ever a good idea: it seems to be susceptible to font size changes, etc...

2017-11-17 16:51 UTC, nigelmegitt commented
> if a 1c height is ever a good idea

I'm fine with it in an example whose purpose is to show something else.

2017-11-20 11:46 UTC, nigelmegitt requested changes
Looks good to me. Something weird is happening with the HTML generation, but the xml source looks good.

2017-11-20 11:46 UTC, nigelmegitt approved these changes

2017-11-20 11:47 UTC, nigelmegitt commented
Apologies for the confusion. I hit the Request changes button instead of approve back there, and then changed it to an approve.

2017-11-23 03:04 UTC, skynavga approved these changes
Doesn't need to rebuild schemas, but no harm perhaps.

2017-11-29 12:23 UTC, nigelmegitt commented
The built version of this PR can be viewed at https://rawgit.com/w3c/ttml1/issues-225-254-section-o-examples-build/index.html

2017-12-12 01:32 UTC, merged