Add note re: semantics of circular actor references
w3c/ttml1 pull request #287
Opened 2017-12-13 03:29 UTC by palemieux

Close #201

2017-12-13 11:23 UTC, nigelmegitt requested changes
Requesting stronger advice to implementers to address the issue.

2017-12-13 11:23 UTC, nigelmegitt commented on spec/ttml1.xml
> +like Steve Coogan in The Trip playing Steve Coogan, two <el>ttm:agent</el> elements are used instead:
The "are used instead" language seems strange - I think this is describing good practice, so this clause could be rephrased:

_the expected practice is to use two `ttm:agent` elements instead:_

2017-12-13 11:23 UTC, nigelmegitt commented on spec/ttml1.xml
> +while the second element (corresponding to Steve Coogan the character) has (i) a <att>type</att> attribute equal to <code>character</code> and (ii) a child <el>ttm:actor</el> element that references
This wording is fine but doesn't address the need to warn implementers that special handling is required. Perhaps something like:

_Despite the lack of defined semantics, it is nevertheless syntactically permitted for a `ttm:actor` element to reference its parent `ttm:agent` element; implementers should take care to handle this situation, for example avoiding infinite loops etc._

2017-12-16 19:09 UTC, palemieux commented
@nigelmegitt The recommendation against circular references is now a _should not_ in light of:

- the original comment at #201
- the comment at https://github.com/w3c/ttml1/issues/201#issuecomment-351272720
- the resolution to issue #213 

The explanation and examples have been split into different notes.

2017-12-17 17:07 UTC, xchange11 approved these changes
Looks good to me.

2017-12-17 22:45 UTC, nigelmegitt approved these changes
Looks good to me. Thanks for making the changes.

2017-12-26 19:22 UTC, merged