State that LWSPs are permitted in tts:fontFamily
w3c/ttml1 pull request #290
Opened 2017-12-14 04:50 UTC by palemieux

Close #248

2017-12-14 13:32 UTC, nigelmegitt approved these changes
Looks good to me. 

For preference I think I'd have added this note after the existing note, but the order of notes is not really important here.

2017-12-15 10:17 UTC, skynavga requested changes

2017-12-15 10:17 UTC, skynavga commented on spec/ttml1.xml
> +attribute is not recommended for maximal compatibilty with processor implementations.
Is there a processor for which this is known to cause a problem?

2017-12-17 13:31 UTC, andreastai approved these changes
Looks good to me. @skynavga Does it resolve your concern if "with processor implementation"? If not, what is your change proposal?

2017-12-26 18:00 UTC, skynavga requested changes

2017-12-26 18:00 UTC, skynavga commented on spec/ttml1.xml
> +attribute is not recommended for maximal compatibilty with processor implementations.
If we don't actually know of an incompatible processor, then please remove "... for maximal compatibility with processor implementations".

2017-12-26 21:27 UTC, palemieux commented
@skynavga This PR reflects the consensus text at #248, which was the result on lengthy discussions which you were part of. Unless information has changed since the drafting of the text and/or you plan on filing a formal objection against the text of the PR, I do not see a compelling reason for the group to spend valuable time reopening this issue.

2017-12-26 22:19 UTC, skynavga commented
I do not accept this change as stated. If you can't point out an affected implementation, then it is mere speculation to suggest there is an incompatibility. While I accept the recommendation against use, I do not accept a motivation based on speculation.

2017-12-26 22:28 UTC, palemieux commented
@skynavga The question is whether you can still live with the consensus text at #248 , which would participated in. If not, i.e. you plan on formally objecting, the group will need to reopen the debate, which will undoubtedly take time away from closing other issues. What say you?

2017-12-26 22:34 UTC, skynavga commented
Feel free to put this on the WG agenda. I do not accept the current text.

2017-12-26 23:00 UTC, nigelmegitt commented
@skynavga you reacted with a thumbs up to https://github.com/w3c/ttml1/issues/248#issuecomment-304038399 to indicate your preference for the option:

> Permit LWSP in document instances but note that some existing processors may not be tolerant of them.

If you have a wording change that would achieves this option in a more satisfactory way to you, please propose it.

2017-12-26 23:30 UTC, skynavga commented
@nigelmegitt how many times shall I repeat myself?

please remove "... for maximal compatibility with processor implementations".

2017-12-26 23:43 UTC, nigelmegitt commented
@skynavga Right, but that's then incomplete, since removing that text means the pull request no longer addresses the consensus "but note that some existing processors may not be tolerant of them" - that's the bit that needs replacement wording please.

2017-12-27 00:10 UTC, skynavga commented
If nobody can point at such a processor, then that statement is factually wrong.

2017-12-27 00:11 UTC, palemieux commented
> If nobody can point at such a processor, then that statement is factually wrong.

These and other many other issues were taken into account while crafting the consensus text at #248. One aspect of the consensus cannot be reopened without reopening it completely. @skynavga What say you?

2018-01-03 17:11 UTC, tairt commented
Could we add for example some text that says something along the line "...because of some ambiguity in TTML 2nd edition that could have led to a different interpretation" and than remove the contentious part "for maximal compatibilty with processor implementations"? Would this work for you @skynavga. 

I agree with @nigelmegitt that without an explaination why this is not recommended it would be incomplete. But I also think that if we re-word it and omit the "processor part" the informative value of the note is still there.

2018-01-03 22:18 UTC, skynavga commented
Firstly, I reject the notion that there has ever been an ambiguity here, or that an implementation that failed to study the relevant specifications and reached the wrong conclusion should be permitted to continue to exist.

Secondly, to my knowledge, nobody has actually pointed out the existence of such an implementation, which to me, means that this the contention that a problem exists is merely conjecture.

My conclusion, is that no change is necessary; however, I do not object to adding a note (for those readers who fail to do their research elsewise)  that says makes the most minimum disrecommendation on the off-chance that such an implementation exists, but I am not willing to make reference to a speculated existence of such an implementation.

Please show me such an implementation, and I would be willing to change my mind.

2018-01-04 16:10 UTC, skynavga approved these changes
Approve with the changed text, and comment yet again that it is not a requirement, and in my opinion, poor practice to document rationale.

2018-01-04 16:13 UTC, merged