Removed redundant clause at 8.4.1.3 Chained Referential Styling
w3c/ttml1 pull request #296
Opened 2017-12-16 06:42 UTC by palemieux

Closes #275

2017-12-16 16:32 UTC, skynavga requested changes

2017-12-16 16:32 UTC, skynavga commented on spec/ttml1.xml
> -<p>If the same style property is specified in more than one referenced
I am opposed to removing this. If there is a problem with it, then let's fix it.

2017-12-17 22:37 UTC, nigelmegitt submitted a review, later dismissed
This is fixing the wrong thing in my opinion - it is the example that is misleading not the sentence being removed here.

2017-12-17 22:41 UTC, palemieux commented
@nigelmegitt @skynavga Please propose a fix to the example then.

2017-12-18 11:53 UTC, nigelmegitt commented
@palemieux @skynavga I don't want to have this discussion in two places at once - right now it seems like it is happening in #275 so I'll wait for something closer to a conclusion there before proposing something additional here. I did propose an alternative example already in that thread.

2018-01-04 07:28 UTC, skynavga commented
I can accept removing the second paragraph of 8.4.1.3 and adding a note under the example as follows:

>__Note:__ The text of the second paragraph in this example is yellow, since ``tts:color='yellow'`` effectively overwrites (is merged over) the ``tts:color='white'`` that style ``s2`` obtains by a reference to style ``s1``.

2018-01-04 16:27 UTC, palemieux commented
Rendered at https://rawgit.com/w3c/ttml1/issue-275-redundance-clause-at-8-4-1-3-build/index.html

2018-01-04 16:27 UTC, skynavga approved these changes

2018-01-04 16:28 UTC, andreastai approved these changes

2018-01-04 16:29 UTC, nigelmegitt commented on spec/ttml1.xml
> -the affected element and proceeds to referenced style sets, and, in turn, to subsequent referenced style sets.</p>
I would still like to add a replacement sentence that explains that when chained referential styling is used each referenced style is fully resolved before the reference is followed.

2018-01-04 16:34 UTC, nigelmegitt reviewed
I don't believe this fully addresses the issue since I would like a clear short sentence to be added in place of the removed paragraph to explain that each referenced style must be resolved into specified styles before being followed.

2018-01-04 16:35 UTC, merged