Make smooth transitions a possibility rather than a recommendation
w3c/ttml1 pull request #306
Opened 2017-12-26 22:01 UTC by palemieux

Closes #304

2017-12-26 22:11 UTC, palemieux commented
Spec at https://rawgit.com/w3c/ttml1/issue-304-smooth-transition-not-preferred-build/index.html

2017-12-26 22:14 UTC, skynavga requested changes
I oppose this change, since the preference was explicitly part of a WG resolution in the past to resolve a CR comment. What we can do, however, is add an additional note clarifying that this preference applies for ITU Region 2, and that other regions may have different preferences.

2017-12-26 23:16 UTC, nigelmegitt approved these changes
Looks good to me.

2017-12-26 23:19 UTC, nigelmegitt commented
@skynavga Pointer to the WG resolution/decision here please? I do not think we need to mention ITU regions - it is up to the implementer to understand which regional preferences apply and therefore whether or not to implement this behaviour. Appending to the version of the text in this pull request something like "This behaviour is preferred in some regions." would be adequate.

2017-12-26 23:20 UTC, palemieux commented
>  is up to the implementer to understand which regional preferences apply and therefore whether or not to implement this behaviour. 

Moreover, smooth transitions is not applicable to all transitions and all circumstances.

2018-01-09 18:53 UTC, skynavga approved these changes

2018-01-09 18:54 UTC, merged