Apply TTML1 2ED errata
w3c/ttml1 pull request #345
Opened 2018-02-27 23:51 UTC by palemieux

See  https://www.w3.org/2013/09/ttml1-errata.html

Closes #226

2018-02-27 23:58 UTC, palemieux commented
Built at https://rawgit.com/w3c/ttml1/issue-226-apply-errata-build/index.html

2018-02-28 15:01 UTC, nigelmegitt requested changes
Just one typo introduced here, everything else looks correct.

2018-02-28 15:01 UTC, nigelmegitt commented on spec/ttml1.xml
> +occur only if <att>tts:wrapOptio</att> is <code>noWrap</code>. Furthermore, when an overflow
typo: s/`tts:wrapOptio`/`tts:wrapOption`

2018-02-28 15:29 UTC, nigelmegitt approved these changes
Thanks!

2018-03-01 15:22 UTC, merged