TTML1 3ED tests
w3c/ttml1 pull request #361
Opened 2018-08-08 21:16 UTC by palemieux

Provides tests for all testable changes from TTML1 2ED to TTML1 3ED, as follows:

- clarified default value blur radius in tts:textOutline (#351):

TextOutline.ttml

- update tts:lineHeight='normal' algorithm to match TTML2 (#355):

_not testable_

- clarified tts:fontSize semantics (#206, #214 and #215):

FontSizeEmInherited.ttml
TwoValueRelativeFontSize.ttml
FontSizeEmRegion.ttml

- specified timing semantics for <br> elements (#339)

BrImplicitDuration.ttml

- clarified tts:direction on <p> elements (#324)

Direction.ttml

- clarified LWSP in color expressions (#322)

Color.html

- clarified validation of undefined items in TT namespaces (#251)

UnknownTTAtribute.ttml

- clarified anonymous span construction, implicit duration for anonymous spans, implicit duration for spans with text nodes exclusively, and implicit duration for <set> (#310, #193)

AnonymousSpanImplicitDuration.ttml
PlainSpanImplicitDuration.ttml
SetImplicitDuration.ttml
  
- clarified that LWSPs are permitted in tts:fontFamily (#248)

FontFamily.ttml

- added initial value fallback to non-inheritable properties (#200)

NonInheritedInitial.ttml

- added <br> to elements to which style applies (#249)

Br.ttml

- specified application defaults for frame rate multiplier and sub-framerate (#192)

_not testable_

- prevent pruning of <br> elements (#197)

Br.ttml

- handled forward interoperability of attribute extensions in TT namespaces (#196)

ForwardInterop.ttml

- prevent <set> elements from being pruned in ISD construction (#216)

Animation.ttml

- clarified that the inherited value of tts:lineHeight='normal' is 'normal' (#220)

LineHeight.ttml

- clarified application of tts:visibility to child elements (#207)

Visibility.ttml

- clarified tts:textDecoration inheritance (#219)

TextDecoration.ttml

- clarified cell metrics for tts:textOutline (#218)

  TextOutline.ttml

- clarified tts:zIndex stacking context (#241)

  ZIndex.ttml

2018-08-09 13:43 UTC, nigelmegitt commented on testsuite/Third Edition/AnonymousSpanImplicitDuration.ttml
> +        No text should be displayed.
Fine point: maybe change to "This text should not be displayed" so if it _is_ displayed that's clearly an error.

2018-08-09 14:40 UTC, skynavga reviewed
Regarding line height tests, the new text that drives this test, "When a single relative `<length>` ...", was previously implied in TTML1 2e, as evidenced by the second sentence in the fourth comment in 8.2.9 of 2e.

2018-08-09 16:36 UTC, nigelmegitt reviewed
Partial review due to lack of time.

2018-08-09 16:36 UTC, nigelmegitt commented on testsuite/Third Edition/BrImplicitDuration.ttml
> +        No text or linebreak<br/>should be displayed.
If text is not displayed but a line break is displayed, presumably that would move the text in the second paragraph down a line. We could highlight that by changing the text of the second paragraph below to say "this text should be displayed at the top" before the break.

2018-08-09 16:36 UTC, nigelmegitt commented on testsuite/Third Edition/Color.ttml
> +<!--Modifications Copyright (c) 2017, Pierre-Anthony Lemieux (pal@palemieux.com)-->
Really? I don't think I've seen a copyright notice on a test suite test before.

2018-08-09 16:36 UTC, nigelmegitt commented on testsuite/Third Edition/Direction.ttml
> +      <p tts:direction="rtl">
Would be worth some kind of note that this only defines weak directionality so it shouldn't be ltr.

2018-08-09 16:36 UTC, nigelmegitt commented on testsuite/Third Edition/Direction.ttml
> +        משמאל לימין<br/>
This text means "left to right" in English.

2018-08-09 16:36 UTC, nigelmegitt commented on testsuite/Third Edition/BrImplicitDuration.ttml
> +        No text or linebreak<br/>should be displayed.
During call, @palemieux pointed out there would be a background colour, and I suggested making it a different colour to the following p.

2018-08-09 18:44 UTC, palemieux commented on testsuite/Third Edition/Color.ttml
> +<!--Modifications Copyright (c) 2017, Pierre-Anthony Lemieux (pal@palemieux.com)-->
Leftover from a long time ago. Fixed at https://github.com/w3c/ttml1/pull/361/commits/32d0ae13c0e0f668634a457f9948651a46dde6a4

2018-09-05 11:24 UTC, nigelmegitt requested changes
Some changes requested, mainly these tests look good.

2018-09-05 11:24 UTC, nigelmegitt commented on testsuite/Third Edition/Br.ttml
> +</tt:tt>
Missing EOL

2018-09-05 11:24 UTC, nigelmegitt commented on testsuite/Third Edition/BrImplicitDuration.ttml
> +      <p begin="0s" end="1s" tts:backgroundColor="blue">
Change to a different background color to distinguish from first paragraph please, as discussed.

2018-09-05 11:24 UTC, nigelmegitt commented on testsuite/Third Edition/Color.ttml
> +</tt:tt>
Missing EOL.

2018-09-05 11:24 UTC, nigelmegitt commented on testsuite/Third Edition/FontFamily.xml
> +      <p begin="0s" end="10s">The last words must be <span tts:fontFamily='InexistantFont, proportionalSerif'>using a proportional serif font</span>.</p>
Unusual use of single quotes here, why not use double quotes as per other attributes and examples?

2018-09-05 11:24 UTC, nigelmegitt commented on testsuite/Third Edition/FontSizeEmInherited.ttml
> +</tt:tt>
Missing EOL.

2018-09-05 11:24 UTC, nigelmegitt commented on testsuite/Third Edition/FontSizeEmRegion.ttml
> +</tt:tt>
Missing EOL.

2018-09-05 11:24 UTC, nigelmegitt commented on testsuite/Third Edition/ForwardInterop.ttml
> +</tt:tt>
Missing EOL.

2018-09-05 11:24 UTC, nigelmegitt commented on testsuite/Third Edition/NonInheritedInitial.ttml
> +</tt:tt>
Missing EOL.

2018-09-05 11:24 UTC, nigelmegitt commented on testsuite/Third Edition/PlainSpanImplicitDuration.ttml
> +        <span>No text should be displayed.</span>
Suggest changing text to "This text should not be displayed" - it is not true that no text should be displayed since the text from line 16 should appear.

2018-09-05 11:24 UTC, nigelmegitt commented on testsuite/Third Edition/PlainSpanImplicitDuration.ttml
> +        <span>Text should displayed.</span>
As per above comment, suggest changing to "This text should be displayed.".

2018-09-05 11:24 UTC, nigelmegitt commented on testsuite/Third Edition/PlainSpanImplicitDuration.ttml
> +</tt:tt>
Missing EOL.

2018-09-05 11:24 UTC, nigelmegitt commented on testsuite/Third Edition/TextDecoration.ttml
> +</tt:tt>
Missing EOL.

2018-09-05 11:24 UTC, nigelmegitt commented on testsuite/Third Edition/SetImplicitDuration.ttml
> +</tt:tt>
Missing EOL.

2018-09-05 11:24 UTC, nigelmegitt commented on testsuite/Third Edition/TextOutline.ttml
> +</tt:tt>
Missing EOL.

2018-09-05 11:24 UTC, nigelmegitt commented on testsuite/Third Edition/TwoValueRelativeFontSize.ttml
> +</tt:tt>
Missing EOL.

2018-09-05 11:24 UTC, nigelmegitt commented on testsuite/Third Edition/UnknownTTAtribute.ttml
> +</tt:tt>
Missing EOL.

2018-09-05 11:24 UTC, nigelmegitt commented on testsuite/Third Edition/Visibility.ttml
> +</tt:tt>
Missing EOL.

2018-09-05 11:24 UTC, nigelmegitt commented on testsuite/Third Edition/ZIndex.ttml
> +</tt:tt>
Missing EOL.

2018-09-05 11:24 UTC, nigelmegitt commented on testsuite/Third Edition/ZIndex.ttml
> +		<div timeContainer="seq">
Using `seq` means that no overlapping regions are created during this test, so no z-order comparisons can be done. Is that correct? Is this test only checking that implementations handle the value space of the `tts:zIndex` style processing?

2018-09-06 14:43 UTC, palemieux commented on testsuite/Third Edition/BrImplicitDuration.ttml
> +        No text or linebreak<br/>should be displayed.
Change color of the second `p`.

2018-09-06 14:47 UTC, palemieux commented on testsuite/Third Edition/Direction.ttml
> +        משמאל לימין<br/>
מימין לשמאל works better?

2018-09-06 16:26 UTC, nigelmegitt commented on testsuite/Third Edition/Direction.ttml
> +        משמאל לימין<br/>
Confirmed with a native Hebrew speaker, that's good.

2018-09-06 16:27 UTC, nigelmegitt commented on testsuite/Third Edition/Direction.ttml
> +        משמאל לימין<br/>
It means "From right to left".

2018-09-07 13:03 UTC, nigelmegitt commented on testsuite/Third Edition/ZIndex.ttml
> +		<div timeContainer="seq">
Discussed in yesterday's TTWG call; the intent here is only to verify that all the values of `tts:zIndex` are supported. They are all valid.

2018-09-07 13:09 UTC, nigelmegitt commented on testsuite/Third Edition/Direction.ttml
> +      <p tts:direction="rtl">
Addressed in b1753b0

2018-09-07 13:10 UTC, nigelmegitt approved these changes

2018-09-07 13:10 UTC, nigelmegitt commented
@palemieux please check you are happy with the changes made in b1753b0 as per the TTWG meeting yesterday.

2018-09-07 14:02 UTC, palemieux commented
@skynavga Are you arguing at https://github.com/w3c/ttml1/pull/361#pullrequestreview-144873178 that `testsuite/Third Edition/TwoValueRelativeFontSize.ttml` is not needed?

2018-09-07 14:11 UTC, nigelmegitt commented
Reviewing https://github.com/w3c/ttml1/pull/361#pullrequestreview-144873178 and comparing 2e with 3e, the substantive change is essentially a movement of text from an informative note to a normative section. Have we got any evidence that the clarified behaviour is what was already implemented? I believe that is what the Director is seeking.

The alternative would be that some implementation supports 2 value font sizes but uses a different basis for calculating the font size dimensions, for example always using the height of the cell as the basis even for the horizontal component.

2018-09-11 16:56 UTC, nigelmegitt commented
Travis build stalled on this, I've restarted it.

2018-09-11 16:57 UTC, nigelmegitt commented
Build succeeded.

2018-09-13 03:58 UTC, palemieux commented
> Have we got any evidence that the clarified behaviour is what was already implemented?

@skynavga Can you confirm that the spec captures current TTPE behavior?

2018-09-13 09:10 UTC, nigelmegitt approved these changes

2018-09-13 14:41 UTC, merged